<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <OutputType>exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK.OpenAL" Version="4.7.4" />
    <PackageReference Include="Helion.OpenALSoft" Version="1.25.2.1" /> 
    <PackageReference Include="Helion.ZMusic" Version="3.0.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\unmanaged\SoundFonts\*" Link="%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
